### ISSUE TITLE
change translations namespace

### ISSUE THREAD

**Issue by mikk150** [udokmeci/yii2-phone-validator#4]
you should not use application translations namespace inside extensions

**Comment by udokmeci** [comment]
You are right. I ll fix the issue with adding at least one language translation.
Thank you for noticing.

**Comment by julianrutten** [comment]
You should really fix this because it kind of causes errors if you are not using PHP message sources and the files are not there because of the following snippet:
https://github.com/yiisoft/yii2/blob/master/framework/i18n/I18N.php#L66

Please use any category but app*

**Comment by udokmeci** [comment]
Merged request. Closed now. Thanks.
