### ISSUE TITLE
Country code validation not work

### ISSUE THREAD

**Issue by jvp777** [udokmeci/yii2-phone-validator#5]
If I send country code "UA" and phone +7 495 968-69-69, validator gives out "true".
Although +7 is the "RU" code.

**Comment by udokmeci** [comment]
Hi,

https://libphonenumber.appspot.com/phonenumberparser?number=+%2B7+495+968-69-69&country=AU

Check out. And are u using `strict = true`?

On April 28, 2017 7:22:14 PM GMT+03:00, jvp777 <notifications@github.com> wrote:
>If I send country code "UA" and phone +7 495 968-69-69, validator gives
>out "true".
>Although +7 is the "RU" code.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/udokmeci/yii2-phone-validator/issues/5

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jvp777** [comment]
Yes 
` ['phone', 'udokmeci\yii2PhoneValidator\PhoneValidator','country'=>'UA','strict'=>true,'format'=>true]`
but validator  gives out "true" for example number +7 495 968-69-69

This is because the function `$phoneUtil->isValidNumber($numberProto)` does not check the regional identity

Here its contents
`
    public function isValidNumber(PhoneNumber $number)
    {
        $regionCode = $this->getRegionCodeForNumber($number);
        return $this->isValidNumberForRegion($number, $regionCode);
    }
`

**Comment by udokmeci** [comment]
Hi there this is related to If you can call the number from UA without problem I guess. The feature you want is missing for now.

Proto has country code, check out.
https://github.com/udokmeci/yii2-phone-validator/blob/master/src/udokmeci/yii2PhoneValidator/PhoneValidator.php#L65
